### ISSUE TITLE
Uncaught Error: Cannot find module "./Main.elm"

### ISSUE THREAD

**Issue by leolorenzoluis** [andrewsuzuki/elm-todo-rest-api#2]
I cloned this repository, run `npm run api` and `npm run dev`, but it's throwing an error.

```
app.js:7535 Uncaught Error: Cannot find module "./Main.elm"webpackMissingModule @ app.js:7535(anonymous function) @ app.js:7535__webpack_require__ @ app.js:20(anonymous function) @ app.js:48__webpack_require__ @ app.js:20(anonymous function) @ app.js:40(anonymous function) @ app.js:43

app.js:99 [WDS] Errors while compiling.

app.js:101 C:\Users\lluis\Source\Repos\elm-todo-rest-api-master\elm-todo-rest-api-master\node_modules\elm-webpack-loader\node_modules\node-elm-compiler\worker.js:96
  errorMessage += `
                  ^
Unexpected token ILLEGAL
 @ ./src/index.js 7:10-31
```

**Comment by andrewsuzuki** [comment]
That illegal token is the start of an es6 template literal, not being used by this package but by the compiler. According to [node.green](http://node.green), template literals appeared in node 4.4. Try upgrading your version of node (or use nvm) to upgrade to the most recent version of node.

**Comment by leolorenzoluis** [comment]
Thanks. Question, how do I fix this? I've enabled CORS on the web server for 8083. Do I need to do something else?
`
XMLHttpRequest cannot load http://localhost:8083/sampledata. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

Also, how do I setup my client side if for example, I'm not going to use elm webpack? I see different ways such as this [http://blog.jessitron.com/2015/11/getting-off-ground-in-elm-project-setup.html](url) to embed Elm.

**Comment by andrewsuzuki** [comment]
What is that error message relevant to? Web server? Port 8083? See the readme, you just have to run `npm run api` and it will spin up a toy server for the api on port 4000...

Setup wouldn't be any different if you didn't want to use webpack, just follow that tutorial you posted and use Main.elm as the input file for `elm-make`. Those questions would be good for /r/elm on reddit or the elm slack.
